import {StyleSheet} from 'react-native';

export const TEXT_STYLES = StyleSheet.create({
  huge: {fontSize: 36, fontWeight: 'bold'},
  h1: {fontSize: 22, fontWeight: 'bold'},
  h2: {fontSize: 20, fontWeight: 'bold'},
  h3: {fontSize: 18, fontWeight: 'bold'},
  h4: {fontSize: 16, fontWeight: 'bold'},
  h5: {fontSize: 14, fontWeight: 'bold'},
  h6: {fontSize: 12, fontWeight: 'bold'},
  h7: {fontSize: 10, fontWeight: 'bold'},
  h8: {fontSize: 8, fontWeight: 'bold'},
  s1: {fontSize: 22, fontWeight: '600'},
  s2: {fontSize: 20, fontWeight: '600'},
  s3: {fontSize: 18, fontWeight: '600'},
  s4: {fontSize: 16, fontWeight: '600'},
  s5: {fontSize: 14, fontWeight: '600'},
  s6: {fontSize: 12, fontWeight: '600'},
  s7: {fontSize: 10, fontWeight: '600'},
  s8: {fontSize: 8, fontWeight: '600'},
  t1: {fontSize: 22},
  t2: {fontSize: 20},
  t3: {fontSize: 18},
  t4: {fontSize: 16},
  t5: {fontSize: 14},
  t6: {fontSize: 12},
  t7: {fontSize: 10},
  t8: {fontSize: 8},
});
